# Generated by Django 3.2.25 on 2025-03-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat', models.CharField(max_length=3000)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=1500)),
                ('Date', models.DateField()),
                ('Reply', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('SecondName', models.CharField(max_length=25)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=25)),
                ('Place', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=1500)),
                ('Rating', models.FloatField()),
                ('Date', models.DateField()),
                ('Expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('File', models.FileField(upload_to='')),
                ('Date', models.DateField()),
                ('Expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.expert')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
                ('Type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.FileField(upload_to='')),
                ('Option1', models.CharField(max_length=3000)),
                ('Option2', models.CharField(max_length=3000)),
                ('Option3', models.CharField(max_length=3000)),
                ('Option4', models.CharField(max_length=3000)),
                ('Answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField()),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Sugession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sugession', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=3000)),
                ('Date', models.DateField()),
                ('Level', models.CharField(max_length=2000)),
                ('Expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.expert')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=3000)),
                ('dtails', models.CharField(max_length=2000)),
                ('Expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.expert')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('SecondName', models.CharField(max_length=25)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=250)),
                ('Place', models.CharField(max_length=150)),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='video_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('Expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.expert')),
            ],
        ),
        migrations.DeleteModel(
            name='Login_table',
        ),
        migrations.AddField(
            model_name='sugession',
            name='TEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.test'),
        ),
        migrations.AddField(
            model_name='sugession',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='result',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.test'),
        ),
        migrations.AddField(
            model_name='feedbackreview',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='expert',
            name='Login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.logintable'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.expert'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='Fromid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='my_app.logintable'),
        ),
        migrations.AddField(
            model_name='chat',
            name='ToId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='my_app.logintable'),
        ),
    ]
