# Generated by Django 3.2.25 on 2025-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_camera_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_language_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.FileField(upload_to='')),
                ('language', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
